# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/lab1/Desktop/lab5b/lab5b/lab5b.srcs/sources_1/ip/singen/singen.xci
# IP: The module: 'singen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lab1/Desktop/lab5b/lab5b/lab5b.srcs/sources_1/ip/singen/singen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'singen'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/lab1/Desktop/lab5b/lab5b/lab5b.srcs/sources_1/ip/singen/singen.xci
# IP: The module: 'singen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lab1/Desktop/lab5b/lab5b/lab5b.srcs/sources_1/ip/singen/singen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'singen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
