# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/mb_system/mb_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system || ORIG_REF_NAME==mb_system} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_microblaze_0_1/mb_system_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_microblaze_0_1 || ORIG_REF_NAME==mb_system_microblaze_0_1} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_clk_wiz_0_3/mb_system_clk_wiz_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_clk_wiz_0_3 || ORIG_REF_NAME==mb_system_clk_wiz_0_3} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_axi_gpio_0_3/mb_system_axi_gpio_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_axi_gpio_0_3 || ORIG_REF_NAME==mb_system_axi_gpio_0_3} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_axi_uartlite_0_3/mb_system_axi_uartlite_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_axi_uartlite_0_3 || ORIG_REF_NAME==mb_system_axi_uartlite_0_3} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_axi_gpio_1_3/mb_system_axi_gpio_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_axi_gpio_1_3 || ORIG_REF_NAME==mb_system_axi_gpio_1_3} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_dlmb_v10_3/mb_system_dlmb_v10_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_dlmb_v10_3 || ORIG_REF_NAME==mb_system_dlmb_v10_3} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_ilmb_v10_3/mb_system_ilmb_v10_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_ilmb_v10_3 || ORIG_REF_NAME==mb_system_ilmb_v10_3} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_dlmb_bram_if_cntlr_3/mb_system_dlmb_bram_if_cntlr_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_dlmb_bram_if_cntlr_3 || ORIG_REF_NAME==mb_system_dlmb_bram_if_cntlr_3} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_ilmb_bram_if_cntlr_3/mb_system_ilmb_bram_if_cntlr_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_ilmb_bram_if_cntlr_3 || ORIG_REF_NAME==mb_system_ilmb_bram_if_cntlr_3} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_lmb_bram_3/mb_system_lmb_bram_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_lmb_bram_3 || ORIG_REF_NAME==mb_system_lmb_bram_3} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_lmb_v10_3/mb_system_lmb_v10_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_lmb_v10_3 || ORIG_REF_NAME==mb_system_lmb_v10_3} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_xbar_1/mb_system_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_xbar_1 || ORIG_REF_NAME==mb_system_xbar_1} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_microblaze_0_axi_periph_1/mb_system_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_microblaze_0_axi_periph_1 || ORIG_REF_NAME==mb_system_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_microblaze_0_axi_intc_0/mb_system_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_system_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_mdm_1_3/mb_system_mdm_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_mdm_1_3 || ORIG_REF_NAME==mb_system_mdm_1_3} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_rst_clk_wiz_0_100M_3/mb_system_rst_clk_wiz_0_100M_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_rst_clk_wiz_0_100M_3 || ORIG_REF_NAME==mb_system_rst_clk_wiz_0_100M_3} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_axi_timer_0_0/mb_system_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_axi_timer_0_0 || ORIG_REF_NAME==mb_system_axi_timer_0_0} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_auto_pc_0/mb_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_auto_pc_0 || ORIG_REF_NAME==mb_system_auto_pc_0} -quiet] -quiet

# XDC: bd/mb_system/mb_system_ooc.xdc
