# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 6
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.cache/wt [current_project]
set_property parent.project_path C:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/hdl/mb_system_wrapper.vhd
add_files C:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/mb_system.bd
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_microblaze_0_1/mb_system_microblaze_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_microblaze_0_1/mb_system_microblaze_0_1_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_microblaze_0_1/mb_system_microblaze_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_clk_wiz_0_3/mb_system_clk_wiz_0_3_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_clk_wiz_0_3/mb_system_clk_wiz_0_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_clk_wiz_0_3/mb_system_clk_wiz_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_axi_gpio_0_3/mb_system_axi_gpio_0_3_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_axi_gpio_0_3/mb_system_axi_gpio_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_axi_gpio_0_3/mb_system_axi_gpio_0_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_axi_uartlite_0_3/mb_system_axi_uartlite_0_3_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_axi_uartlite_0_3/mb_system_axi_uartlite_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_axi_uartlite_0_3/mb_system_axi_uartlite_0_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_axi_gpio_1_3/mb_system_axi_gpio_1_3_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_axi_gpio_1_3/mb_system_axi_gpio_1_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_axi_gpio_1_3/mb_system_axi_gpio_1_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_dlmb_v10_3/mb_system_dlmb_v10_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_dlmb_v10_3/mb_system_dlmb_v10_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_ilmb_v10_3/mb_system_ilmb_v10_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_ilmb_v10_3/mb_system_ilmb_v10_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_dlmb_bram_if_cntlr_3/mb_system_dlmb_bram_if_cntlr_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_ilmb_bram_if_cntlr_3/mb_system_ilmb_bram_if_cntlr_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_lmb_bram_3/mb_system_lmb_bram_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_lmb_v10_3/mb_system_lmb_v10_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_lmb_v10_3/mb_system_lmb_v10_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_xbar_1/mb_system_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_microblaze_0_axi_intc_0/mb_system_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_microblaze_0_axi_intc_0/mb_system_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_microblaze_0_axi_intc_0/mb_system_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_mdm_1_3/mb_system_mdm_1_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_mdm_1_3/mb_system_mdm_1_3_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_mdm_1_3/mb_system_mdm_1_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_rst_clk_wiz_0_100M_3/mb_system_rst_clk_wiz_0_100M_3_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_rst_clk_wiz_0_100M_3/mb_system_rst_clk_wiz_0_100M_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_rst_clk_wiz_0_100M_3/mb_system_rst_clk_wiz_0_100M_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_axi_timer_0_0/mb_system_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_axi_timer_0_0/mb_system_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_auto_pc_0/mb_system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/mb_system_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_microblaze_0_1/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top mb_system_wrapper -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mb_system_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mb_system_wrapper_utilization_synth.rpt -pb mb_system_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
