# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_axi_timer_0_0/mb_system_axi_timer_0_0.xci
# IP: The module: 'mb_system_axi_timer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_axi_timer_0_0/mb_system_axi_timer_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_system_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_axi_timer_0_0/mb_system_axi_timer_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_system_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_axi_timer_0_0/mb_system_axi_timer_0_0.xci
# IP: The module: 'mb_system_axi_timer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_axi_timer_0_0/mb_system_axi_timer_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_system_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lab1/Desktop/project_microblaze_nexys/project_microblaze_nexys.srcs/sources_1/bd/mb_system/ip/mb_system_axi_timer_0_0/mb_system_axi_timer_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_system_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
